const ALERT='ALERT'
const REFETCH_CHATS='REFETCH_CHATS'

export const NEW_MESSAGE_ALERT='NEW MESSAGE ALERT'
export const NEW_ATTACHMENTS='NEW ATTACHMENTS'
export const NEW_REQUEST='NEW REQUEST'
export const NEW_MESSAGE='NEW MESSAGE'
export const START_TYPING='START_TYPING'
export const STOP_TYPING='STOP_TYPING'

export {ALERT,REFETCH_CHATS}